force-app/main/default/objects/CertificationAnswer__c/CertificationAnswer__c.object-meta.xml
<CustomObject>
    <label>Certification Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>CertificationAnswer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CertificationAnswers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CertificationAnswer__c/fields/CertificationQuestion__c.field-meta.xml
<CustomField>
    <fullName>CertificationQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Question</label>
    <referenceTo>CertificationQuestion__c</referenceTo>
    <relationshipLabel>CertificationAnswers</relationshipLabel>
    <relationshipName>CertificationAnswers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CertificationAnswer__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CertificationAnswer__c/fields/IsRightAnswer__c.field-meta.xml
<CustomField>
    <fullName>IsRightAnswer__c</fullName>
    <label>Is Right Answer</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CertificationQuestion__c/CertificationQuestion__c.object-meta.xml
<CustomObject>
    <label>Certification Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Certification Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certification Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CertificationQuestion__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CertificationQuestion__c/fields/QuestionText__c.field-meta.xml
<CustomField>
    <fullName>QuestionText__c</fullName>
    <label>Question text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CertificationQuestion__c/fields/RightAnswersCount__c.field-meta.xml
<CustomField>
    <fullName>RightAnswersCount__c</fullName>
    <label>RightAnswersCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CertificationQuestion__c/fields/Tip__c.field-meta.xml
<CustomField>
    <fullName>Tip__c</fullName>
    <label>Tip</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CertificationService.cls
public with sharing class CertificationService {
    public static void synchroniseQuestionsAnswers(){
        Map<String, String> questionMap = new Map<String, String>();

        for (CertificationQuestion__c question : [SELECT Id, ExternalId__c, QuestionText__c FROM CertificationQuestion__c]) {
            questionMap.put(question.ExternalId__c, question.Id);
        }
        List<CertificationAnswer__c> answersForUpdate = new List<CertificationAnswer__c>();
        List<CertificationAnswer__c> answersForDelete = new List<CertificationAnswer__c>();
        List<CertificationAnswer__c> answers = [SELECT Id, ExternalId__c, CertificationQuestion__c, Value__c FROM CertificationAnswer__c];
        for (CertificationAnswer__c answer : answers) {
            if (questionMap.containsKey(answer.ExternalId__c)) {
                if (answer.Value__c.startsWithIgnoreCase('?')) {
                    answer.Value__c = answer.Value__c.removeStartIgnoreCase('?').trim();
                }
                if (answer.Value__c.startsWithIgnoreCase('A.')) {
                    answer.Value__c = answer.Value__c.removeStartIgnoreCase('A.');
                }
                if (answer.Value__c.startsWithIgnoreCase('B. ')) {
                    answer.Value__c = answer.Value__c.removeStartIgnoreCase('B.');
                }
                if (answer.Value__c.startsWithIgnoreCase('C. ')) {
                    answer.Value__c = answer.Value__c.removeStartIgnoreCase('C.');
                }
                if (answer.Value__c.startsWithIgnoreCase('D. ')) {
                    answer.Value__c = answer.Value__c.removeStartIgnoreCase('D.');
                }
                answer.Value__c = answer.Value__c.trim();
                if (String.isBlank(answer.Value__c)) {
                    answersForDelete.add(answer);
                } else {
                    answer.CertificationQuestion__c = questionMap.get(answer.ExternalId__c);
                    answersForUpdate.add(answer);
                }
            }
        }
        update answersForUpdate;
        delete answersForDelete;
        System.debug(answersForUpdate.size() + ' have been updated.');
        System.debug(answersForDelete.size() + ' have been deleted.');
    }

    public static List<CertificationModel.Question> getQuestions () {
        List<CertificationModel.Question> result = new List<CertificationModel.Question>();
        for (CertificationQuestion__c certificationQuestion : [SELECT Id, QuestionText__c, Tip__c, RightAnswersCount__c,  (SELECT Value__c, IsRightAnswer__c FROM CertificationAnswers__r ORDER BY Value__c), (SELECT Resource__c FROM Tips__r) FROM CertificationQuestion__c]) {
            CertificationModel.Question question = new CertificationModel.Question();
            question.question = certificationQuestion.QuestionText__c;
            question.tip = certificationQuestion.Tip__c;
            question.id = certificationQuestion.Id;
            question.answers = new List<CertificationModel.Answer>();
            question.tips = new List<String>();
            for (CertificationAnswer__c certificationAnswer : certificationQuestion.CertificationAnswers__r) {
                CertificationModel.Answer answer = new CertificationModel.Answer();
                answer.answer = certificationAnswer.Value__c;
                answer.isValid = certificationAnswer.IsRightAnswer__c == 1;
                question.answers.add(answer);
            }
            for (Tip__c tip : certificationQuestion.Tips__r) {
                question.tips.add(tip.Resource__c);
            }
            result.add(question);
        }
        result.sort();
        return result;
    }
}